[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  included_files = [
    ".next/server/**/*.js",
    ".next/server/**/_devPagesManifest.json",
    ".next/server/**/_devMiddlewareManifest.json",
    ".next/server/**/_middlewareManifest.json"
  ] 